from __future__ import annotations

from typing import Any, Callable


class ID:
    def __init__(self, c_id: Any, lib: Any) -> None: ...
    def to_string(self) -> str: ...


class Message:
    def __init__(self, message: Any, lib: Any, refs: Any) -> None: ...
    def publish(self, data: bytes) -> None: ...
    def publish_ex(self, id_obj: ID, data: bytes) -> None: ...
    def send(self, id_obj: ID, data: bytes) -> None: ...


class Callback:
    def __init__(self, callback: Any, lib: Any, fns: Any, refs: Any) -> None: ...
    def on_ready(self, fn: Callable[[ID], None]) -> None: ...
    def on_connect(self, fn: Callable[[ID], None]) -> None: ...
    def on_disconnect(self, fn: Callable[[ID], None]) -> None: ...
    def on_message(self, fn: Callable[[ID, bytes], None]) -> None: ...


class Event(Message, Callback):
    def __init__(self, event: Any, lib: Any, fns: Any, refs: Any) -> None: ...


class Runnable:
    def __init__(self, runnable: Any, lib: Any, fns: Any, refs: Any) -> None: ...
    def run(self) -> None: ...
    def poll(self) -> None: ...
    def stop(self) -> None: ...
    def restart(self) -> None: ...
    def dispatch(self, fn: Callable[[], None]) -> None: ...


class WebTransaction:
    def __init__(self, transaction: Any, lib: Any) -> None: ...
    def set_content_type(self, content_type: str) -> None: ...
    def send(self, data: bytes) -> None: ...
    def get_route(self) -> str: ...


class Web(Runnable):
    def __init__(self, web: Any, lib: Any, fns: Any, refs: Any) -> None: ...
    def on_ready(self, fn: Callable[[ID], None]) -> None: ...
    def on_get(self, fn: Callable[[WebTransaction], bool]) -> None: ...
    def use_ws(self, route: str) -> Event: ...
    def destroy(self) -> None: ...


class Standalone(Event, Runnable):
    def __init__(self, standalone: Any, lib: Any, fns: Any, refs: Any) -> None: ...
    def destroy(self) -> None: ...


class Gateway(Standalone):
    def __init__(self, gateway: Any, lib: Any, fns: Any, refs: Any) -> None: ...
    def add_service(self, service: Event) -> None: ...
    def destroy(self) -> None: ...


class Module:
    def __init__(self) -> None: ...
    def create_gateway(self) -> Gateway: ...
    def create_udp_client(self, host: str, port: int, buffer: int) -> Standalone: ...
    def create_udp_server(self, host: str, port: int, buffer: int) -> Standalone: ...
    def create_tcp_client(self, host: str, port: int, buffer: int) -> Standalone: ...
    def create_tcp_server(self, host: str, port: int, buffer: int) -> Standalone: ...
    def create_ws_client(self, host: str, port: int, route: str, buffer: int) -> Standalone: ...
    def create_ws_server(self, host: str, port: int, route: str, buffer: int) -> Standalone: ...
    def create_http_server(self, host: str, port: int, buffer: int) -> Web: ...


def create_gateway() -> Gateway: ...

def create_udp_client(host: str, port: int, buffer: int) -> Standalone: ...

def create_udp_server(host: str, port: int, buffer: int) -> Standalone: ...

def create_tcp_client(host: str, port: int, buffer: int) -> Standalone: ...

def create_tcp_server(host: str, port: int, buffer: int) -> Standalone: ...

def create_ws_client(host: str, port: int, route: str, buffer: int) -> Standalone: ...

def create_ws_server(host: str, port: int, route: str, buffer: int) -> Standalone: ...

def create_http_server(host: str, port: int, buffer: int) -> Web: ...


__all__: list[str]
